#! /usr/bin/env bash
# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse off
yabai -m config window_placement second_child
yabai -m config window_topmost off
yabai -m config window_opacity off
# yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow off
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.97
yabai -m config split_ratio 0.50
yabai -m config auto_balance off
# yabai -m config mouse_modifier               fn
# yabai -m config mouse_action1                move
# yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout bsp
#               external_bar [<main|all|off>:<top_padding>:<bottom_padding>]
yabai -m config external_bar all:36:0
yabai -m config top_padding 18
yabai -m config bottom_padding 18
yabai -m config left_padding 18
yabai -m config right_padding 18
yabai -m config window_gap 12

# borders
yabai -m config window_border off
# yabai -m config window_border_width 8
# yabai -m config active_window_border_color 0xff5E81AC
# # yabai -m config normal_window_border_color 0xff3B4252
# yabai -m config normal_window_border_color 0xff4c566a

# signals
yabai \
	-m signal \
	--add \
	event=display_added \
	action="$HOME/.config/yabai/apply-labels &> /tmp/apply-labels.log"
# action="$HOME/bin/handle-monitor &> /tmp/handle-monitor.log"

yabai \
	-m signal \
	--add \
	event=display_removed \
	action="$HOME/.config/yabai/apply-labels &> /tmp/apply-labels.log"
# action="$HOME/bin/handle-monitor &> /tmp/handle-monitor.log"

# focus window after active space changes
# yabai \
#   -m signal \
#   --add event=space_changed \
#   action="yabai -m window --focus \$($HOME/.config/yabai/first-window-id)"

# # focus window after active display changes
# yabai \
#   -m signal \
#   --add event="display_changed" \
#   action="yabai -m window --focus \$($HOME/.config/yabai/first-window-id)"

# set up labels
$HOME/.config/yabai/apply-labels

# application to space rules
# yabai -m rule --add app="^Safari$" space="browser"
yabai -m rule --add app="^Slack$" space="chat"
yabai -m rule --add app="^Rambox.*" space="mail"
yabai -m rule --add app="^Messages$" space="messages"
# yabai -m rule --add app="^Chrome$" space="scratch"
yabai -m rule --add app="^kitty$" space="terminal"

# floating non-standard windows
yabai -m rule --add label="Finder" app="^Finder\$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari\$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)\$" manage=off
yabai -m rule --add label="System Preferences" app="^System Preferences\$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator\$" manage=off
yabai -m rule --add label="Pixelmator" app="^Pixelmator\$" manage=off
yabai -m rule --add label="mpv" app="^mpv\$" sticky=off layer=normal manage=on
yabai -m rule --add label="Firfox PIP" app="^Firefox\$" title="^(Picture-in-Picture)\$" manage=on
yabai -m rule --add label="Stupid Zoom Bar" app="^zoom.us\$" title="^zoom share (statusbar|toolbar) window\$" manage=off

# start up sketchybar
killall sketchybar &>/dev/null
brew services restart felixkratz/formulae/sketchybar

echo "yabai configuration loaded.."
