-- -- vimwiki/vimwiki
-- vim.g.vimwiki_list = {
--   {
--     path = '~/Dropbox/Notes/vimwiki/';
--     syntax = 'markdown';
--     ext = '.md';
--     auto_diary_indx = 1;
--   }
-- }
-- vim.g.vimwiki_conceallevel = 0
-- vim.g.vimwiki_folding = ''
