#!/bin/bash

# pmset -g batt | grep -o '[0-9]*%' | head -c 3
# echo '|'
# pmset -g batt | grep "'.*'" | sed "s/'//g" | cut -c 18-19
# echo '|'
# ps -axC -o %cpu | awk '{s+=$1} END {print s}'
# echo '|'
# ps -A -o %mem | awk '{s+=$1} END {print "" s}'
# echo '|'
# osascript -e 'set ovol to output volume of (get volume settings)'
# echo '|'
# osascript -e 'output muted of (get volume settings)'

battery_percentage=$(pmset -g batt | grep -o '[0-9]*%' | head -c 3)
charging_status=$(pmset -g batt | grep "'.*'" | sed "s/'//g" | cut -c 18-19)
cpu_percentage=$(ps -axC -o %cpu | awk '{s+=$1} END {print s}')
memory_percentage=$(ps -A -o %mem | awk '{s+=$1} END {print "" s}')
volume_percentage=$(osascript -e 'set ovol to output volume of (get volume settings)')
muted_status=$(osascript -e 'output muted of (get volume settings)')

echo "{
  \"batteryPercentage\": \"${battery_percentage}\",
  \"chargingStatus\": \"${charging_status}\",
  \"cpuPercentage\": \"${cpu_percentage}\",
  \"memoryPercentage\": \"${memory_percentage}\",
  \"volumePercentage\": \"${volume_percentage}\",
  \"mutedStatus\": \"${muted_status}\"
}"
