return {}
-- return {
-- 	{
-- 		"nvim-neorg/neorg",
-- 		build = ":Neorg sync-parsers",
-- 		dependencies = { { "nvim-lua/plenary.nvim" } },
-- 		opts = {
-- 			load = {
-- 				["core.concealer"] = {
-- 					config = {
-- 						icon_preset = "diamond",
-- 					},
-- 				},
-- 				["core.defaults"] = {},
-- 				["core.dirman"] = { -- Manages Neorg workspaces
-- 					config = {
-- 						workspaces = {
-- 							notes = "~/Dropbox/Notes/neorg",
-- 							programs = "~/Dropbox/Notes/tac/programs",
-- 							journal = "~/Dropbox/Notes/journal",
-- 						},
-- 						default_workspace = "notes",
-- 					},
-- 				},
-- 				["core.export"] = {},
-- 				["core.summary"] = {},
-- 				-- ["core.tempus"] = {}, dates
-- 				["core.integrations.treesitter"] = {},
-- 			},
-- 		},
-- 	},
-- }
